//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamTbl()
        {
            this.Exam_Result_Tbl = new HashSet<Exam_Result_Tbl>();
            this.QuestionsTbls = new HashSet<QuestionsTbl>();
        }
    
        public int Ex_ID { get; set; }
        public int Prof_ID { get; set; }
        public string Ex_Name { get; set; }
        public string Ex_Info { get; set; }
        public int Ex_Total { get; set; }
        public int Ex_Munite_Duration { get; set; }
        public System.DateTime Ex_Start_On { get; set; }
        public System.DateTime Ex_End_On { get; set; }
        public int Ex_Passing_Mark { get; set; }
        public int Course_ID { get; set; }
        public bool IsShow { get; set; }
    
        public virtual CourseTbl CourseTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Result_Tbl> Exam_Result_Tbl { get; set; }
        public virtual ProfessorTbl ProfessorTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionsTbl> QuestionsTbls { get; set; }
    }
}
