//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingTbl
    {
        public int Faculty_ID { get; set; }
        public Nullable<int> Firstparking_ID { get; set; }
        public Nullable<int> Secparking_ID { get; set; }
        public Nullable<int> Thirdparking_ID { get; set; }
    }
}
