//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostTbl()
        {
            this.Post_Reply_Tbl = new HashSet<Post_Reply_Tbl>();
        }
    
        public int Post_ID { get; set; }
        public string Post_Content { get; set; }
        public System.DateTime Post_Date { get; set; }
        public Nullable<int> St_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Reply_Tbl> Post_Reply_Tbl { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
