//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessorTbl()
        {
            this.ExamTbls = new HashSet<ExamTbl>();
            this.Prof_Course_Tbl = new HashSet<Prof_Course_Tbl>();
            this.QrTbls = new HashSet<QrTbl>();
        }
    
        public int Prof_ID { get; set; }
        public string Prof_Name { get; set; }
        public string Prof_Email { get; set; }
        public string Prof_Pass { get; set; }
        public Nullable<bool> IsAccepted { get; set; }
        public string Prof_Subject { get; set; }
        public byte[] Prof_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamTbl> ExamTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prof_Course_Tbl> Prof_Course_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QrTbl> QrTbls { get; set; }
    }
}
