//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsTbl
    {
        public int Ex_ID { get; set; }
        public int Question_ID { get; set; }
        public string Question { get; set; }
        public string First_Choice { get; set; }
        public string Second_Choice { get; set; }
        public string Third_Choice { get; set; }
        public string Correct_Choice { get; set; }
        public string Fourth_Choice { get; set; }
        public int Degree { get; set; }
    
        public virtual ExamTbl ExamTbl { get; set; }
    }
}
