//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterCoursesTbl
    {
        public int IdRegister { get; set; }
        public int St_ID { get; set; }
        public int Course_ID { get; set; }
        public bool IsApprove { get; set; }
    
        public virtual CourseTbl CourseTbl { get; set; }
        public virtual StudentTbl StudentTbl { get; set; }
    }
}
