//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTbl()
        {
            this.Attendtbls = new HashSet<Attendtbl>();
            this.Exam_Result_Tbl = new HashSet<Exam_Result_Tbl>();
            this.Post_Reply_Tbl = new HashSet<Post_Reply_Tbl>();
            this.PostTbls = new HashSet<PostTbl>();
            this.RegisterCoursesTbls = new HashSet<RegisterCoursesTbl>();
        }
    
        public int St_ID { get; set; }
        public string St_Name { get; set; }
        public string St_Email { get; set; }
        public string St_Password { get; set; }
        public Nullable<int> Dep_ID { get; set; }
        public byte[] St_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendtbl> Attendtbls { get; set; }
        public virtual DepartmentTbl DepartmentTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_Result_Tbl> Exam_Result_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_Reply_Tbl> Post_Reply_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostTbl> PostTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterCoursesTbl> RegisterCoursesTbls { get; set; }
    }
}
